name: Incorrect albums assigned to track
description: Mark a track which is displaying the wrong associated albums on its page
labels: ['type:track_incorrect_albums']
body:
  - type: input
    id: link
    attributes:
      label: Link
      description: Can you provide the link to the page on Last.fm?
      placeholder: "e.g. https://www.last.fm/music/The+Weeknd/_/Gasoline"
    validations:
      required: true
  - type: textarea
    id: sources
    attributes:
      label: What did you expect?
      description: Which albums did you expect to be linked to
      placeholder: "The track showed the album 'After Hours', but I was expecting 'Dawn FM'..."
    validations:
      required: true
